export VISUAL=nvim
export EDITOR=nvim

alias vim="nvim"
alias battery="upower -i $(upower -e | grep '/battery') | grep --color=never -E percentage|xargs|cut -d' ' -f2|sed s/%//"
alias bookmark="$EDITOR ~/dotfiles/bookmarks"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

export PATH="~/dotfiles/bash_scripts/scripts:$PATH"

set -o vi
