:highlight Pmenu ctermbg=gray guibg=gray

if has('win32')
	call plug#begin('~/vimfiles/plugged')
		Plug 'neoclide/coc.nvim', {'branch': 'release'}
	call plug#end()
else
	call plug#begin('~/.vim/plugged')
		Plug 'Valloric/YouCompleteMe'
	call plug#end()
endif

" Source the cocscript.vim
source ~/dotfiles/vim/cocscript.vim
