if has('win32')
	call plug#begin('~/vimfiles/plugged')
		Plug 'neoclide/coc.nvim', {'branch': 'release'}
	call plug#end()
else
	call plug#begin('~/.vim/plugged')
		Plug 'Valloric/YouCompleteMe'
	call plug#end()
endif

set t_Co=256

source ~/dotfiles/vim/cocscript.vim

if has('gui')
	colorscheme morning
else
	colorscheme desert
endif
