#!/usr/bin/env bash

# LaTeX files
latexmk -output-directory=/home/srabon/Documents/pdfs/ -pdf /home/srabon/dotfiles/progress/progress.tex
latexmk -output-directory=/home/srabon/Documents/pdfs/ -pdf /home/srabon/Zettelkasten/6\ -\ Main\ Notes/Data\ Science/statistics.tex

latexmk -output-directory=/home/srabon/Documents/pdfs/gre/ -pdf /home/srabon/Zettelkasten/6\ -\ Main\ Notes/GRE/Quant.tex

# Django ORM Notes
pandoc -i /home/srabon/Zettelkasten/6\ -\ Main\ Notes/Django\ ORM\ Deep\ Dive.md -o /home/srabon/Documents/pdfs/Django\ ORM\ Deep\ Dive.pdf

# GRE
pandoc -i /home/srabon/Zettelkasten/6\ -\ Main\ Notes/GRE/TC\ \&\ SE.md -o /home/srabon/Documents/pdfs/gre/TC\ \&\ SE.html
pandoc -i /home/srabon/Documents/pdfs/gre/TC\ \&\ SE.html -o /home/srabon/Documents/pdfs/gre/TC\ \&\ SE.pdf

pandoc -i /home/srabon/Zettelkasten/6\ -\ Main\ Notes/GRE/Vocab.md -o /home/srabon/Documents/pdfs/gre/Vocab.html
pandoc -i /home/srabon/Documents/pdfs/gre/Vocab.html -o /home/srabon/Documents/pdfs/gre/Vocab.pdf

# cleanup
rm /home/srabon/Documents/pdfs/*.aux
rm /home/srabon/Documents/pdfs/*.fdb_latexmk
rm /home/srabon/Documents/pdfs/*.fls
rm /home/srabon/Documents/pdfs/*.log

rm /home/srabon/Documents/pdfs/gre/*.aux
rm /home/srabon/Documents/pdfs/gre/*.fdb_latexmk
rm /home/srabon/Documents/pdfs/gre/*.fls
rm /home/srabon/Documents/pdfs/gre/*.log

rm /home/srabon/Documents/pdfs/*.html
rm /home/srabon/Documents/pdfs/gre/*.html
