#!/usr/bin/bash

DATE_TIME_NOW=$(date +"%I:%M %p, %A, %e %b %Y")

echo -e "\nPerforming the following actions, \n"
echo -e "git add .\ngit commit -m "$1 -- at $DATE_TIME_NOW"\ngit push\n"

git add .
git commit -m "$1 -- at $DATE_TIME_NOW"
git push
