#!/usr/bin/env bash

fbname=$(basename "$1" .md)

echo -e "Compiling $fbname.md to $fbname.pdf\n"
echo -e "Executing: \n"
echo -e "pandoc -i "$fbname.md" -o "$fbname.pdf" --katex"

pandoc -s -i "$fbname.md" -o "$fbname.pdf" --katex
