#!/usr/bin/env bash

cd $HOME/dotfiles/10moons-driver-vin1060plus/
source $HOME/dotfiles/10moons-driver-vin1060plus/venv/bin/activate
echo "$1" | sudo -S $HOME/dotfiles/10moons-driver-vin1060plus/venv/bin/python $HOME/dotfiles/10moons-driver-vin1060plus/driver.py -d
